name: build-apk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: "platform-tools platforms;android-36 build-tools;36.0.0"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: "8.13"

      - name: Build debug APK
        run: gradle assembleDebug --stacktrace --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v5
        with:
          name: aimassist-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
